### PR TITLE
Add error classes

### PR DESCRIPTION
**Pull request by benhutchins**
Add error classes to thrown errors.
Also update the README a bit.

### CODE REVIEW

**Comment by drudge** [comment]
Thanks for your contribution, @benhutchins! I've published to npm as v`1.3.0`.

**Comment by benhutchins** [comment]
@drudge what's your opinion on cross platforming this? I looked at node-xkeychain fork and it's pretty terrible, was considering cleaning it up and making a PR to merge here, rather than making another fork

**Comment by drudge** [comment]
@benhutchins I guess it depends on what that entails. I like to keep dependencies small. I've rejected PR that require native add-ons or shelling out to alternate interpreted scripts. I'm not opposed to it, I just want to keep the module as lean as possible.

**Comment by benhutchins** [comment]
@drudge So ES6-ing it up and breaking support with most older versions of Node.js isn't an improvement? Hmm.

I agree with you on all counts. I specifically used this repo because it didn't add 1000 dependencies to get it to work. I don't actually like that `node-keychain` relies on executing the `/usr/bin/security`, as it binds the application that can request access to `security`, allowing anything on the system to execute `/usr/bin/security` and retrieve the password. Far too open to attack right now to use for anything actually sensitive, I think my first attempt would be to actually fix that.

**Comment by benhutchins** [comment]
@drudge What do you think of this https://github.com/drudge/node-keychain/compare/master...benhutchins:feature/bh/ffi?expand=1

It converts to using FFI, which adds a dependency, but provides native binding to talk to the Objective-C Security library. This means your process is reading the password directly which tells the system to lock it to your executable. During development, that would be `node`, but when compiling node into a self-contained binary it properly locks to your signed application.

This significantly improved the security, where `node-keychain` currently is unsuitable for anything sensitive making it borderline useless. I think that makes it worth adding the dependencies.

Using `node-ffi` over a direct bundled `node-gyp` allows for easier native binding to other platforms, which I can add support for following this.

Just an FYI, this is a WIP. I need node-ffi/node-ffi#363 merged before this will actually work.

**Pull request merged**
